// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVdVGdVmeP5mlikvbQF3AkdQ3JNOg_uco',
    appId: '1:674085318891:web:00dfb59d7e720c1ca24eae',
    messagingSenderId: '674085318891',
    projectId: 'buski-74e3a',
    authDomain: 'buski-74e3a.firebaseapp.com',
    storageBucket: 'buski-74e3a.firebasestorage.app',
    measurementId: 'G-DFB2M6XMT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZl1sVfBhwniVA5xIt05PGeApvYrjnc0Q',
    appId: '1:674085318891:android:645d1772fac9325ea24eae',
    messagingSenderId: '674085318891',
    projectId: 'buski-74e3a',
    storageBucket: 'buski-74e3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyA--64cda1bcju76YwCHnwdahG5Wsip4',
    appId: '1:674085318891:ios:4f994ac359dc4476a24eae',
    messagingSenderId: '674085318891',
    projectId: 'buski-74e3a',
    storageBucket: 'buski-74e3a.firebasestorage.app',
    iosBundleId: 'com.berk.buskiTeaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyA--64cda1bcju76YwCHnwdahG5Wsip4',
    appId: '1:674085318891:ios:4f994ac359dc4476a24eae',
    messagingSenderId: '674085318891',
    projectId: 'buski-74e3a',
    storageBucket: 'buski-74e3a.firebasestorage.app',
    iosBundleId: 'com.berk.buskiTeaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVdVGdVmeP5mlikvbQF3AkdQ3JNOg_uco',
    appId: '1:674085318891:web:c38f6747767bef50a24eae',
    messagingSenderId: '674085318891',
    projectId: 'buski-74e3a',
    authDomain: 'buski-74e3a.firebaseapp.com',
    storageBucket: 'buski-74e3a.firebasestorage.app',
    measurementId: 'G-4BBRT698GY',
  );
}